name: docker-publish
on:
  workflow_call:
    inputs:
      imageFullName:
        required: true
        type: string
      version:
          required: true
          type: string
      dockerfilePath:
        required: false
        default: ./Dockerfile
        type: string
      dockerRepo:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_URL:
        required: false
      DOCKER_USERNAME:
        required: false
      DOCKER_PASSWORD:
        required: false

jobs:
  publish:
      needs: version
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout"
          uses: actions/checkout@v2

        - name: "Docker Login"
          run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}" ${{ secrets.DOCKER_REGISTRY_URL }}

        - name: Build Image
          run: |
            DOCKER_BUILDKIT=1 docker build . --build-arg BUILD_VERSION=${{ inputs.version }} --tag image --file ${{ inputs.dockerfilePath }} --target prod --progress=plain

        - name: Push image
          run: |
            docker tag image ${{ inputs.imageFullName }}
            docker push ${{ inputs.IMAGE_FULL_NAME }}
