name: ci
on:
  workflow_call:
    inputs:
      stack:
        required: true
        type: string
      appName:
        required: true
        type: string
      publishImage:
        required: true
        type: string
      runPulumi:
        required: true
        type: string
      pulumiPreview:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_URL:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      CI_NPM_TOKEN:
        required: true
      GOOGLE_CREDENTIALS:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true

jobs:
  publish:
    uses: proxima-one/github-workflows/.github/workflows/go-service.yml@master
    with:
      appName: ${{ inputs.appName }}
      publish: ${{ inputs.publishImage }}
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

  pulumi:
    if: ${{ inputs.runPulumi }}
    needs: publish
    uses: proxima-one/github-workflows/.github/workflows/pulumi-service.yml@master
    with:
      stack: ${{ inputs.stack }}
      pulumiPath: ./deploy
      preview: ${{ inputs.pulumiPreview }}
      publishedImageId: ${{ needs.publish.outputs.publishedImageId }}
      publishedVersion: ${{ needs.publish.outputs.publishedVersion }}
    secrets:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      CI_NPM_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
