name: node-lib-lerna
on:
  workflow_call:
    inputs:
      publish:
        required: false
        default: false
        type: boolean
      preview:
        required: false
        default: false
        type: boolean
      preid:
        required: false
        default: dev
        type: string
    secrets:
      CI_NPM_TOKEN:
        required: true
      CI_PUBLIC_NPM_TOKEN:
        required: false

jobs:
  quick-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: "Setup npm"
        run: |
          npm set @proxima-one:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.CI_NPM_TOKEN }}"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

  publish:
    if: ${{ inputs.publish }}
    needs: quick-check
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Checkout all branches and tags, needed for lerna

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: "Setup npm"
        run: |
          npm set @proxima-one:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.CI_NPM_TOKEN }}"
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.CI_PUBLIC_NPM_TOKEN }}"

      - name: Install Dependencies
        run: |
          yarn install

      - name: Publish Canary Version
        id: publish_canary
        if: ${{ inputs.preview }}
        env:
          GH_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          lerna publish --canary --preid ${{ inputs.preid }}.${{ github.run_number }} --dist-tag ${{ inputs.preid }} --yes --no-verify-access 2>&1 | tee publish_output
          published_versions=$(sed -n 's/^lerna success published \(@.* .*\)$/\1/p' publish_output)
          rm publish_output
          
          echo "PUBLISHED_VERSIONS<<EOF" >> $GITHUB_ENV
          echo "$published_versions" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Comment a version
        if: ${{ github.event_name == 'pull_request' && inputs.preview }}
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: |
            <b>Released new canary packages:</b>
            ```
            ${{ env.PUBLISHED_VERSIONS }}
            ```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Version and publish"
        if: ${{ !inputs.preview }}
        env:
          GH_TOKEN: ${{ secrets.CI_NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          
          lerna version --conventional-commits --conventional-graduate --yes
          lerna publish from-git --yes --no-verify-access
