name: Pulumi
on:
  workflow_call:
    inputs:
      pulumiPath:
        required: true
        type: string
      stack:
        required: false
        default: proxima-one/default
        type: string
      proximaNode:
        required: false
        default: "amur"
        type: string
      preview:
        required: false
        default: true
        type: boolean
      publishedImageId:
        required: true
        type: string
      publishedVersion:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_URL:
        required: true
      CI_NPM_TOKEN:
        required: true
      GOOGLE_CREDENTIALS:
        required: true
      PULUMI_ACCESS_TOKEN:
        required: true
      GITHUB_ACCESS_TOKEN:
        required: false

env:
  USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
  update:
    name: ${{ (inputs.preview && 'Preview') || 'Up' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest changes
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Setup Private NPM Registry
        run: |
          npm set @proxima-one:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.CI_NPM_TOKEN }}"

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ inputs.pulumiPath }}
      
      - name: GCP Auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Pulumi preview changes
        if: ${{ inputs.preview }}
        uses: pulumi/actions@v4
        with:
          command: preview
          work-dir: ${{ inputs.pulumiPath }}
          stack-name: ${{ inputs.stack }}
          comment-on-pr: true
        env:
          PROXIMA_NODE: ${{ inputs.proximaNode }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY_URL }}${{ inputs.publishedImageId }}
          VERSION: ${{ inputs.publishedVersion }}

      - name: Pulumi apply changes
        if: ${{ !inputs.preview }}
        uses: pulumi/actions@v4
        with:
          command: up
          work-dir: ${{ inputs.pulumiPath }}
          stack-name: ${{ inputs.stack }}
          github-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
          PROXIMA_NODE: ${{ inputs.proximaNode }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY_URL }}${{ inputs.publishedImageId }}
          VERSION: ${{ inputs.publishedVersion }}
