name: read-version
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      dockerRepo:
        required: true
        type: string
    secrets:
      DOCKER_REGISTRY_URL:
        required: true
    outputs:
        version:
          description: "Version of image"
          value: ${{ jobs.readVersion.outputs.version }}
        imageTag:
          description: "Image tag of image"
          value: ${{ jobs.readVersion.outputs.imageTag }}
        imageId:
          description: "Id (url without Docker registry) of image"
          value: ${{ jobs.readVersion.outputs.imageId }}
        imageFullName:
          description: "URL (with Docker registry) of image"
          value: ${{ jobs.readVersion.outputs.imageId }}

jobs:
  readVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      imageTag: ${{ steps.version.outputs.IMAGE_TAG }}
      imageId: ${{ steps.version.outputs.IMAGE_ID }}
      imageFullName: ${{ steps.version.outputs.IMAGE_FULL_NAME }}
    steps:
      - name: "Read Version"
        id: version
        working-directory: .
        run: |
          pwd
          ls
